{
 "title": "my_exporter_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "My_exporter status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"localhost:9000\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "free_RAM", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Load CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "avg_load", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Free ROM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "free_ROM", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}